### ISSUE TITLE
Working on O3DS but freezes when closes

### ISSUE THREAD

**Issue by kurocygnus** [nedwill/fasthax#16]
Tried the new build, got the "we won" message but when I press start it presents some messages too much fast to read and when it's suppose to close and come back to homebrew menu, bot screen stay with a red color.

(I know it's in alpha, just reporting what I experienced)

**Comment by GravitySuitCollector** [comment]
o3ds 11.2.0-35U ofw here. Here is what I'm getting with what I just built less than 20 minutes ago (no dumps because ofw). As for the whole thing with pressing start, I think nedwill is just detecting if start is being held, and not if there are separate presses. You have to tap start pretty fast because of that in order to see what I got. A simple oversight, could probably be remedied with waiting for two states (a start button up, then start button down).

I myself am getting:
`[+] UAF succeeded and backdoor installed.`
`[-] Couldn't finalize global backdoor.`
`[-] We won't be able to run kernel code in other processes`
`k11_exploit failed!`
`waiting for user... press <start> to continue`
When I press start as prompted, I get a red screen freeze. It has been consistent each time it succeeds with the red screen freeze.

**Comment by nedwill** [comment]
That error is expected. I didn't implement `finalize_global_backdoor` yet.

**Comment by kurocygnus** [comment]
Oh, good to know!

**Comment by grifnelle** [comment]
Does anyone have the build of the most recent file for o3ds?

**Comment by nedwill** [comment]
@grifnelle It's not usable by anyone yet. I'll publish a build when it's usable :)

**Comment by nedwill** [comment]
Also there's only one build for all 3DSes because we can detect the kernel version now that this is a homebrew application!

**Comment by grifnelle** [comment]
@nedwill oh okay Thanks Ned, Ive been making your updates known on the reddit and people are pretty happy- keep up the good work :)

**Comment by ghost** [comment]
@nedwill That means it will work on 2DS too? We will be able to install legit CIA's and/or non-legit CIA's through FBI Cia Installer?

**Comment by nedwill** [comment]
This is now fixed in the beta. When the exploit succeeds, it no longer freezes when exiting. Thanks for the report!
