### ISSUE TITLE
Cleanup after exploit

### ISSUE THREAD

**Issue by nedwill** [nedwill/fasthax#2]
When the UAF happens we overwrite a free pointer, so we should go through the KTimer slab heap and make everything consistent again. I know how to do this if it's not obvious to others.

See https://github.com/nedwill/fasthax/blob/master/source/exploit.c#L100

**Comment by kade-robertson** [comment]
While this isn't technically related, I was reading through `check_control()` trying to comprehend everything so I could try and help out. I see `LINEAR_KERN_TO_USER` is only used once, and it is operating on the constant `TIMER2_NEXT_KERNEL`. Is there any reason that this needed to be written this way rather than the result of the formula `0x1681100c`, like being region or console-specific?

Regarding the actual cleanup, are you referring to data being left over after both the timer handles are closed? Apologies if these questions have simple answers, I'm not really familiar with developing for 3DS at all and my C is a bit rusty.

**Comment by nedwill** [comment]
That's because the actual data written in memory to the timer is that first constant, and then we're viewing it from userspace through the second. You shouldn't constant fold constants like that pre-emptively IMO.

For the actual cleanup, everything is fine once the exploit is done but we have a freed timer in userspace. We just need to scan for the missing timer object and patch up the freed linked list, so when the exploit program returns we don't have a dangling pointer to a freed timer object in userspace.

**Comment by kade-robertson** [comment]
Ah, okay. I think someone other than myself will have to do this (especially if you know how to already). Switching between work and meetings and this is proving quite difficult to actually remember anything :stuck_out_tongue:

**Comment by nedwill** [comment]
This is now implemented.
