### ISSUE TITLE
o3DS freezes after local backdoor is installed

### ISSUE THREAD

**Issue by shadowninja108** [nedwill/fasthax#26]
Version: 11.2
Entrypoint: Soundhax
Running latest build (like new new). I see two possible methods causing freeze: "finalize_global_backdoor" and "cleanup_uaf". Tried same build with n3DS and worked.

**Comment by SlyCedix** [comment]
Having the same issue on a N3DSXL 11.2.0.35U

`[+] UAF succeeded and local backdoor installed.`

is the last thing I see, then the 3DS freezes

Used both Soundhax and OoT3Dhax as entrypoints, same results from both

**Comment by kurocygnus** [comment]
I don't know after what build happened, but won't work anymore on o3DS. Before, the exploit worked but gave the red screen. Now, it hangs without showing the "we won!" message.

**Comment by nedwill** [comment]
Yeah it's broken atm don't worry. It'll get worse before it gets better. Just need to rethink the cleanup a bit since it's complicated and very prone to mistakes. Basically other processes are grabbing our timers as we're trying to clean up, and I think backing up/restoring the user heap where the freed object ended up revealed a UAF happening with that object in the kernel that I wasn't aware of before. I should be able to work around this though.

At this point all the stages are implemented so after squashing all the bugs it'll be done (beta). Then reliability improvements can be made iteratively from a working base.

**Comment by ShinichiKudoSan** [comment]
@nedwill how long will it take are you know anything? I'll checked out abit of code but i cant help you sorry mate :/ Is there no debugger to trigger the "empty slots"?

**Comment by Irastris** [comment]
@ShinichiKudoSan Probably sometime tomorrow, as I believe he's back on another plane now.

**Comment by ShinichiKudoSan** [comment]
@Irastris I think this night it will be released as beta (3.1. prob. 00.pm) and then we all can hack our console :D

**Comment by mariogamer2** [comment]
@ShinichiKudoSan the big problem is that nintendo can simply patch safehax,because we actually running SAFE_MODE who have firmlaunchhax so... Prepare for an update :P...

The weird thing is that they didn't updated it... Maybe there's some explanation...

**Comment by ShinichiKudoSan** [comment]
@mariogamer2 thats because they see the github repo and doesn't know how it works, or? :'D
Yeah they can fix it speedly, but i think they let us a little bit time when the beta comes out which works and then you see New System Update 11.3 :DDD

**Comment by tesnos6921** [comment]
@newwill O3DS 11.1.0-35U here, not sure if this will help but from the debugging I did (I don't know much C) it seems to crash on line 70 of backdoor.c, when kreadint_real is called from line 139 of exploit.c.  Also, luma tells me it is a prefetch abort, not sure what that is.

**Comment by shadowninja108** [comment]
Wait that is the global backdoor method, but hasn't it not installed a global backdoor yet?

**Comment by tesnos6921** [comment]
@shadowninja108 No, this is it using the global backdoor to cleanup.  I looked up what prefetch abort is, and it seems like the issue is that KTIMER_POOL_HEAD is not the same across all versions so the program attempts to read the value of something that doesn't exist, causing a crash.  (I'm probably wrong, but that is what it looks like to me)

**Comment by tesnos6921** [comment]
Changing KTIMER_POOL_HEAD to 0xFFF31278 taken from [here](https://www.3dbrew.org/wiki/Virtual_address_mapping_FW3F) seems to cause a change.  Rather than luma reporting the error's process as dlplay, it reports it as [sm](https://www.3dbrew.org/wiki/Services)

**Comment by kasai07** [comment]
old3ds eur 11.2 
freeze 

/* patch the broken timer to point to the abandoned node */
  u32 *ktimer_head = (u32 *)kreadint_real((u32 *)KTIMER_POOL_HEAD);

**Comment by lotsa-spaghetti** [comment]
For me it crashes even before the cleanup, it seems to freeze somewhere at finalizing the backdoor. So there seems to be a different bug (o3DS 11.2E)

**Comment by lotsa-spaghetti** [comment]
Just tried some debugging, crash seems to happen when the global backdoor has been finalized and it checks if it has been done correctly [backdoor.c L228, `return global_backdoor_installed();`](https://github.com/nedwill/fasthax/blob/master/source/backdoor.c#L228). Removing the check and returning true progresses to the cleanup and crashes there again. Very weird.

**Comment by kev1ncal** [comment]
It gives a black screen on old 3ds 11.2 U

**Comment by kev1ncal** [comment]
Freezes for me on old 3DS 11.2 on 0x2000

**Comment by nedwill** [comment]
Now when the local backdoor is successfully installed, it should no longer crash due to added offsets.
