### ISSUE TITLE
Including fasthax in a build breaks svchax.

### ISSUE THREAD

**Issue by ghost** [nedwill/fasthax#37]

**Comment by nedwill** [comment]
Probably because fasthax needs to change the size of the linear heap in order to make the UAF land somewhere predictable: https://github.com/nedwill/fasthax/blob/master/source/heap.c

**Comment by nedwill** [comment]
This is why I'm trying to design fasthax around launching independently. Bundling fasthax into an app should mean you just use the backdoor I provide to grab any additional privs you want without worrying about maintaining fasthax itself. Bundling a hacky thing is easier atm, but long term I believe launching separately will alleviate issues like this.

**Comment by nedwill** [comment]
I'll mark this as an issue to be addressed for the final release. We'll have to decide how to resolve this one way or another. Let me know your thoughts.

**Comment by Steveice10** [comment]
Ahh, I didn't notice that you reimplemented __system_allocateHeaps, that explains it. I am also trying to design a solution independent of other apps. However, rather than just fasthax, I wanted to make something that will also run svchax on firmware versions unsupported by fasthax, hence the inclusion of both in one app.

I noticed in heap.c that you have a TODO for making sure ctrulib doesn't try to use the extra linear memory and overwrite the exploited object. With that in mind, couldn't you allocate another temporary block of linear memory separately in the exploit process with svcControlMemory, rather than adding to ctrulib's linear heap?

**Comment by Steveice10** [comment]
Alternatively, simply leaving a few extra pages free would probably solve the issue, as having none available is likely the reason for the crash.

**Comment by Steveice10** [comment]
As a final note, it seems as of 3 days ago, ctrulib has a much larger default linear heap size of 32MB, so your changes may no longer be necessary.

**Comment by nedwill** [comment]
@Steveice10 do you have a repo where you're trying to do this? I was hoping to keep fasthax separated out but I'd be happy to make small changes specifically to help you out. I understand the appeal of having an all-in-one privesc app.

**Comment by Steveice10** [comment]
I kind of scrapped the idea, but the solution that worked for me was to update ctrulib, set __ctru_heap_size to a low value, and not include the fasthax heap.c file in the build.

The basic issue is that svchax needs to use svcControlMemory to allocate a few linear pages for the exploit process, so a few need to be left free for it to function. Since the ctrulib allocation code update a few days ago, this is only a matter of lowering the main heap size variable. Plus, since the default linear heap size is now 32MB, your changes to make it 30MB shouldn't be needed anymore, I think.

**Comment by nedwill** [comment]
I think I tried that but it wasn't working until I overrode the allocation function. It's super gross though and I wouldn't mind killing that file.

**Comment by nedwill** [comment]
Yeah, once those changes make it to stable ctrulib I'll look forward to fixing that up.
