### ISSUE TITLE
Patch kernel and sm to skip access checks instead of patching ACL and PID

### ISSUE THREAD

**Issue by ghost** [nedwill/fasthax#43]

**Comment by nedwill** [comment]
We do have the backdoor in both 0x30 and 0x7b, but I do agree it's not really an ideal situation. My hope was that a kernel exploit can be separated as much as possible from whatever privileged operations another process wants to do. I think it's reasonable that if someone wants to run an exploit, they probably want the increased privs anyways, so I'd be open to patching the kernel, thought that would add complexity/maintenance.

**Comment by Steveice10** [comment]
So basically, fasthax/etc. would be responsible for providing a backdoor, and the application is left to do any other service access tricks and what not itself, okay.

I do believe it would be ideal to at least standardize on SVC 0x7B for compatibility purposes. The patch I currently have worked out for permanent SVC access simply looks from 0xDFF00000 to 0xE0000000 for "1B 0E 1A E1" and replaces it with "01 A0 B0 E3", stubbing the ACL check. Rather than at runtime, you could also include this search in find_addr.py and hardcode the addresses into the version map.

**Comment by nedwill** [comment]
Alright, as long as the patch is that simple I'm fine with guaranteeing the presence of 0x7b.

**Comment by Steveice10** [comment]
See https://github.com/nedwill/fasthax/pull/44
